POST http://localhost:8080/api/posts/create
Content-Type: application/json

{
    "uid": 415,
    "content": "get dog"
}


###
GET http://localhost:8080/api/posts/all

###
GET http://localhost:8080/api/posts/415

